version: '3'

services:
  db:
    image: postgres:latest
    container_name: express-mvc-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: express-mvc-api
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: